name: Tag and Sync Version

# Trigger on push to master or via manual GitHub UI
on:
  push:
    branches: [master]  # Adjust to 'main' if that's your default branch
  workflow_dispatch:

# Allow GitHub Actions to commit and tag
permissions:
  contents: write

jobs:
  tag-version:
    # Skip if the trigger was a GitHub bot (prevents infinite loops)
    if: github.actor != 'github-actions'
    name: Tag and Update Version
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (adjust version to match your frontend project)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Match your frontend’s Node version

      # Step 3: Bump the minor version in version.txt (e.g., 1.2.3 → 1.3.0)
      - name: Bump version (minor)
        id: bump
        run: |
          OLD_VERSION=$(cat version.txt)
          MAJOR=$(echo "$OLD_VERSION" | cut -d. -f1)
          MINOR=$(echo "$OLD_VERSION" | cut -d. -f2)
          PATCH=$(echo "$OLD_VERSION" | cut -d. -f3)

          NEW_MINOR=$((MINOR + 1))
          NEW_VERSION="$MAJOR.$NEW_MINOR.0"

          echo "$NEW_VERSION" > version.txt
          echo "BUMPED_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "Bumped from $OLD_VERSION to $NEW_VERSION"

      # Step 4: Output the new version (for logging)
      - name: Echo Version
        run: |
          echo "New version: ${{ env.BUMPED_VERSION }}"

      # Step 5: Commit the version.txt change back to the master branch
      - name: Commit version bump
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add version.txt
          git commit -m "chore: bump version to ${{ env.BUMPED_VERSION }}" || echo "No changes to commit"
          git push

      # Step 6: Tag the commit with a version (e.g., v1.3.0) and push tag
      - name: Tag and Push
        run: |
          git tag v${{ env.BUMPED_VERSION }}
          git push origin v${{ env.BUMPED_VERSION }}
